# Generated by Django 2.2.16 on 2021-04-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096, unique=True, verbose_name='Вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096, unique=True, verbose_name='Название опроса')),
                ('description', models.CharField(max_length=4096, verbose_name='Описание опроса')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала опроса')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096, unique=True, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('CUSTOM', 'CUSTOM'), ('SINGLE', 'SINGLE'), ('MULTIPLE', 'MULTIPLE')], default='SINGLE', max_length=8)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to='app.Poll', verbose_name='Название опроса')),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона пользователя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта пользователя')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Poll', verbose_name='Название опроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session', verbose_name='Идентификатор сессии пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_answer', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Текстовый ответ пользователя')),
                ('choices', models.ManyToManyField(blank=True, related_name='user_choices', to='app.Choice', verbose_name='Варианты ответа пользователя')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question', verbose_name='Название вопроса')),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='app.UserForm', verbose_name='Анкета пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='app.Question', verbose_name='Название вопроса'),
        ),
    ]
